version: '3.8'

services:
  root_app:
    build: ./root-nestjs-api
    ports:
      - "3000:3000"
    volumes:
      - ./root-nestjs-api/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3000

  users_microservice:
    build: ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: yarn start:dev

  payments_microservice:
    build: ./payments-microservice
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: yarn start:dev

  nats:
    image: nats
    ports:
      - 4222:4222

  mysql_bd:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=0410M!123@
      - MYSQL_DATABASE=nestjs_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=0410M!123@
      - MYSQL_TCP_PORT=3307
